### ISSUE TITLE
php-amqp 1.7.1

### ISSUE THREAD

**Issue by thomasvargiu** [prolic/HumusAmqp#24]
[php-amqp 1.7.1](https://github.com/pdezwart/php-amqp/tree/v1.7.1) doesn't have `AMQPBasicProperties` that is present only in `master` branch

**Comment by prolic** [comment]
This is intended - currently you have to compile php-amqp from master in order to use this library. This library will be updated as soon as php-amqp releases a new version.

The 1.7.1 release of php-amqp has some issues that are only fixed in current master and this would lead to serious problems with this library.
